const foods = [
    {
        id: 1,  
        name: "Doughlicious",
        category: "dessert",
        image: "https://images.pexels.com/photos/3026801/pexels-photo-3026801.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "₹ 300",
        description: "Belgian chocolate glazed donuts, icing with sprinkles on top",
    },
    {
        id: 2,
        name: "Pizza",  
        category: "maindish",
        image: "https://images.pexels.com/photos/2619967/pexels-photo-2619967.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "₹ 500",
        description: "Bite into the goodness of Italian pizza with extra cheese",
    },
    {
        id: 3,
        name: "Taco",
        category: "maindish",
        image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "₹ 200",
        description: "Mexican tortilla folded with chicken, cheese and lettuce",
    },
    {
        id: 4,
        name: "Samosa",
        category: "breakfast",
        image: "https://images.pexels.com/photos/1639567/pexels-photo-1639567.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "₹ 50",
        description: "Crispy, golden-brown pastry filled with spicy potatoes and peas",
    },
    {
        id: 5,
        name: "Chole Bhature",
        category: "breakfast",
        image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "₹ 150",
        description: "Fluffy deep-fried bread served with spicy chickpea curry",
    },
    {   id: 6,
        name: "Chocolate Milkshake",
        category: "drinks",
        image: "https://images.pexels.com/photos/3026801/pexels-photo-3026801.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "₹ 120",
        description: "Rich and creamy chocolate milkshake topped with whipped cream",
    },
]
export default foods;